language: java
jdk:
- oraclejdk8
sudo: false
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify

after_success:
  - mvn jacoco:report coveralls:report

notifications:
  email:
    on_failure: always